# Generated by Django 5.1.3 on 2024-11-21 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                ("area_id", models.IntegerField(primary_key=True, serialize=False)),
                ("area_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="CrimeCode",
            fields=[
                ("crm_cd_id", models.AutoField(primary_key=True, serialize=False)),
                ("crm_cd", models.IntegerField()),
                ("crm_cd_desc", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CrimeLocation",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                ("location", models.CharField(max_length=100)),
                ("lat", models.DecimalField(decimal_places=7, max_digits=10)),
                ("lon", models.DecimalField(decimal_places=7, max_digits=10)),
                (
                    "cross_street",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Premise",
            fields=[
                ("premis_cd", models.IntegerField(primary_key=True, serialize=False)),
                ("premis_desc", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "status_code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("status_desc", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Timestamp",
            fields=[
                ("timestamp_id", models.AutoField(primary_key=True, serialize=False)),
                ("date_occ", models.DateField()),
                ("time_occ", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "email",
                    models.EmailField(max_length=40, primary_key=True, serialize=False),
                ),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Weapon",
            fields=[
                ("weapon_cd", models.IntegerField(primary_key=True, serialize=False)),
                ("weapon_desc", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ReportingDistrict",
            fields=[
                ("rpt_dist_no", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.area"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CrimeReport",
            fields=[
                ("dr_no", models.BigIntegerField(primary_key=True, serialize=False)),
                ("date_rptd", models.DateField()),
                ("mocodes", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "area_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.area"
                    ),
                ),
                (
                    "crm_cd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_crime",
                        to="api.crimecode",
                    ),
                ),
                (
                    "crm_cd_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="secondary_crime",
                        to="api.crimecode",
                    ),
                ),
                (
                    "crm_cd_3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tertiary_crime",
                        to="api.crimecode",
                    ),
                ),
                (
                    "crm_cd_4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quaternary_crime",
                        to="api.crimecode",
                    ),
                ),
                (
                    "location_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.crimelocation",
                    ),
                ),
                (
                    "premis_cd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.premise"
                    ),
                ),
                (
                    "rpt_dist_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.reportingdistrict",
                    ),
                ),
                (
                    "status_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.status"
                    ),
                ),
                (
                    "timestamp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.timestamp"
                    ),
                ),
                (
                    "weapon_cd",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.weapon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Victim",
            fields=[
                ("vict_id", models.AutoField(primary_key=True, serialize=False)),
                ("vict_age", models.IntegerField()),
                ("vict_sex", models.CharField(blank=True, max_length=1, null=True)),
                ("vict_descent", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "dr_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.crimereport",
                    ),
                ),
            ],
        ),
    ]
