version: "3.8"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      # POSTGRES_SERVER: db # Set PostgreSQL server
      POSTGRES_USER: postgres # Set PostgreSQL user
      POSTGRES_PASSWORD: example # Set PostgreSQL password
      POSTGRES_DB: LA_Crimes # Set PostgreSQL database
    volumes:
      - pgdata:/var/lib/postgresql/data
    # network_mode: "host"
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network

    # network_mode: "host"
    #   - app-network

  python_app:
    build:
      context: . # Use the current directory to build
      dockerfile: Dockerfile # Specify the Dockerfile for the Python script
    depends_on:
      - db
    networks:
      - app-network

volumes:
  pgdata:
networks:
  app-network:
